Repository NorESMhub/BLOM, pull requests merged in 2022-11, with the labels that each got.

#201 Fix porosity read
  hamocc/mo_read_sedpor.F90
Labels: bug, iHAMOCC

#205 Correct unit of diagnostic field and make conservation and checksum diagnostics selectable by namelist options
  cime_config/buildnml
  phy/mod_budget.F90
  phy/mod_checksum.F90
  phy/mod_dia.F
  phy/rdlim.F
  tests/fuk95/limits
Labels: bug, enhancement

#202 pCO2, Piston velocity and solubility output
  cime_config/buildnml
  hamocc/accfields.F90
  hamocc/carchm.F90
  hamocc/mo_bgcmean.F90
  hamocc/mo_carbch.F90
  hamocc/ncout_hamocc.F90
Labels: enhancement, iHAMOCC

#208 Bugfix pnetcdf
  hamocc/read_netcdf_var.F90
  hamocc/write_netcdf_var.F90
Labels: bug, iHAMOCC
