Repository NorESMhub/BLOM, pull requests merged in 2022-09, with the labels that each got.

#190 Merge branch 'master' into 'feature-hamocc_beyond-CMIP6'
  cime_config/buildnml
  drivers/cpl_mct/ocn_comp_mct.F90
  hamocc/hamocc4bcm.F90
  hamocc/hamocc_init.F
  hamocc/hamocc_init.F90
  hamocc/hamocc_step.F
  hamocc/hamocc_step.F90
  hamocc/meson.build
  hamocc/mo_apply_ndep.F90
  hamocc/mo_apply_oafx.F90
  hamocc/mo_control_bgc.F90
  hamocc/mo_read_fedep.F90
  hamocc/mo_read_ndep.F90
  hamocc/mo_read_oafx.F90
  hamocc/ncout_hamocc.F
  hamocc/ncout_hamocc.F90
  hamocc/restart_hamoccwt.F
  hamocc/restart_hamoccwt.F90
  hamocc/trc_limitc.F
  hamocc/trc_limitc.F90
  phy/mod_config.F90
  phy/restart_rd.F
Labels: iHAMOCC

#192 Dynamic mapping of pore water tracers to ocean tracers
  hamocc/dipowa.F90
  hamocc/hamocc_init.F90
  hamocc/mo_param1_bgc.F90
Labels: iHAMOCC

#189 Lon-lat variable sediment porosity
  cime_config/buildnml
  hamocc/bodensed.F90
  hamocc/dipowa.F90
  hamocc/hamocc_init.F90
  hamocc/inventory_bgc.F90
  hamocc/meson.build
  hamocc/mo_control_bgc.F90
  hamocc/mo_read_sedpor.F90
  hamocc/mo_sedmnt.F90
  hamocc/powach.F90
  hamocc/powadi.F90
  hamocc/sedshi.F90
Labels: enhancement, iHAMOCC

#194 BUG fixes: sediment alkalinity and sediment C14
  hamocc/powach.F90
Labels: bug, iHAMOCC

#198 Fixing variable sediment porosity - field initialization in case of `sedbypass=true`
  hamocc/bodensed.F90
  hamocc/dipowa.F90
  hamocc/hamocc_init.F90
  hamocc/meson.build
  hamocc/mo_sedmnt.F90
Labels: iHAMOCC
