Repository NorESMhub/BLOM, pull requests merged in 2023-08, with the labels that each got.

#262 add BLOM regression test functionality
  cime_config/buildnml
  cime_config/config_component.xml
  cime_config/config_compsets.xml
  cime_config/config_pes.xml
  cime_config/ocn_in.readme
  cime_config/testdefs/testlist_blom.xml
  cime_config/testdefs/testmods_dirs/blom/wavice/user_nl_cice
  cime_config/testdefs/testmods_dirs/blom/wavice/user_nl_cpl
  phy/mod_dia.F
Labels: bug, enhancement

#261 Feature iHAMOCC nml
  cime_config/buildnml
  cime_config/ocn_in.readme
  hamocc/aufr_bgc.F90
  hamocc/beleg_parm.F90
  hamocc/beleg_vars.F90
  hamocc/hamocc_init.F90
  hamocc/meson.build
  hamocc/mo_param_bgc.F90
  hamocc/ocprod.F90
Labels: enhancement, iHAMOCC

#268 Merging master into feature-hamocc_beyond-CMIP6
  cime_config/buildnml
  cime_config/config_component.xml
  cime_config/config_compsets.xml
  cime_config/config_pes.xml
  cime_config/ocn_in.readme
  cime_config/testdefs/testlist_blom.xml
  cime_config/testdefs/testmods_dirs/blom/wavice/user_nl_cice
  cime_config/testdefs/testmods_dirs/blom/wavice/user_nl_cpl
  hamocc/aufr_bgc.F90
  hamocc/aufw_bgc.F90
  hamocc/beleg_parm.F90
  hamocc/beleg_vars.F90
  hamocc/carchm.F90
  hamocc/hamocc4bcm.F90
  hamocc/hamocc_init.F90
  hamocc/meson.build
  hamocc/mo_boxatm.F90
  hamocc/mo_param_bgc.F90
  hamocc/ocprod.F90
  hamocc/sedshi.F90
  phy/mod_dia.F
Labels: iHAMOCC

#263 refactor buildnml to use the CIME-CCS python based namelist generation capabilities
  bld/tnx1v4/patch.input.128
  cime_config/ParamGen/README.ipynb
  cime_config/ParamGen/XML_NML.ipynb
  cime_config/ParamGen/paramgen.py
  cime_config/ParamGen/paramgen_utils.py
  cime_config/ParamGen/xml_schema/entry_id_pg.xsd
  cime_config/buildcpp
  cime_config/buildnml
  cime_config/case_dict.py
  cime_config/config_component.xml
  cime_config/config_pes.xml
  cime_config/namelist_definition_blom.xml
  cime_config/ocn_in_paramgen.py
  cime_config/testdefs/testlist_blom.xml
  cime_config/user_nl_blom
Labels: enhancement
