Repository NorESMhub/BLOM, pull requests merged in 2023-10, with the labels that each got.

#280 remove #ifdefs from HAMOCC
  .github/workflows/ci.yml
  cesm/mod_cesm.F90
  cime_config/ocn_in.readme
  drivers/nuopc/mod_nuopc_methods.F90
  drivers/nuopc/ocn_comp_nuopc.F90
  hamocc/accfields.F90
  hamocc/aufr_bgc.F90
  hamocc/aufw_bgc.F90
  hamocc/beleg_vars.F90
  hamocc/carchm.F90
  hamocc/cyano.F90
  hamocc/dipowa.F90
  hamocc/hamocc4bcm.F90
  hamocc/hamocc_init.F90
  hamocc/inventory_bgc.F90
  hamocc/mo_apply_ndep.F90
  hamocc/mo_apply_rivin.F90
  hamocc/mo_bgcmean.F90
  hamocc/mo_biomod.F90
  hamocc/mo_boxatm.F90
  hamocc/mo_carbch.F90
  hamocc/mo_control_bgc.F90
  hamocc/mo_intfcblom.F90
  hamocc/mo_param1_bgc.F90
  hamocc/mo_param_bgc.F90
  hamocc/mo_sedmnt.F90
  hamocc/ncout_hamocc.F90
  hamocc/ocprod.F90
  hamocc/powach.F90
  hamocc/profile_gd.F90
  hamocc/sedshi.F90
  phy/mod_ifdefs.F90
  phy/restart_wt.F
  trc/mod_tracers.F90
  trc/restart_trcrd.F90
Labels: enhancement, iHAMOCC

#284 Update ci.yml with ecosys enabled
  .github/workflows/ci.yml
  trc/restart_trcrd.F90
Labels: iHAMOCC, CI/meson

#291 Add capability to run OAE experiments with an OmegaA threshold
  cime_config/namelist_definition_blom.xml
  hamocc/mo_apply_oafx.F90
  hamocc/mo_read_oafx.F90
Labels: iHAMOCC

#293 hotfix for line length issue
  hamocc/accfields.F90
  hamocc/aufw_bgc.F90
Labels: iHAMOCC

#281 migrate HAMOCC config settings to run time namelist settings
  cime_config/buildcpp
  cime_config/buildnml
  cime_config/config_component.xml
  cime_config/namelist_definition_blom.xml
  cime_config/testdefs/testlist_blom.xml
  cime_config/testdefs/testmods_dirs/blom/hamocc1/user_nl_blom
  cime_config/testdefs/testmods_dirs/blom/hamocc2/user_nl_blom
  drivers/mct/import_mct.F
  drivers/nuopc/mod_nuopc_methods.F90
  hamocc/hamocc4bcm.F90
  hamocc/hamocc_init.F90
  hamocc/mo_control_bgc.F90
  hamocc/mo_param1_bgc.F90
Labels: iHAMOCC
