Repository NorESMhub/BLOM, pull requests merged in 2024-12, with the labels that each got.

#441 Always allocate shelfmask array
  hamocc/mo_read_shelfmask.F90
Labels: iHAMOCC

#443 Revert moving hamocc tests to separate directory
  cime_config/testdefs/testlist_blom.xml
  cime_config/testdefs/testmods_dirs/blom/hamocc/hamocc1/shell_commands
  cime_config/testdefs/testmods_dirs/blom/hamocc/hamocc1/user_nl_blom
  cime_config/testdefs/testmods_dirs/blom/hamocc/hamocc2/shell_commands
  cime_config/testdefs/testmods_dirs/blom/hamocc/hamocc2/user_nl_blom
Labels: iHAMOCC

#445 Revert moving hamocc tests to separate directory
  cime_config/testdefs/testlist_blom.xml
  cime_config/testdefs/testmods_dirs/blom/hamocc/hamocc1/shell_commands
  cime_config/testdefs/testmods_dirs/blom/hamocc/hamocc1/user_nl_blom
  cime_config/testdefs/testmods_dirs/blom/hamocc/hamocc2/shell_commands
  cime_config/testdefs/testmods_dirs/blom/hamocc/hamocc2/user_nl_blom
Labels: iHAMOCC

#444 Revert moving hamocc tests to separate directory
  cime_config/testdefs/testlist_blom.xml
  cime_config/testdefs/testmods_dirs/blom/hamocc/hamocc1/shell_commands
  cime_config/testdefs/testmods_dirs/blom/hamocc/hamocc1/user_nl_blom
  cime_config/testdefs/testmods_dirs/blom/hamocc/hamocc2/shell_commands
  cime_config/testdefs/testmods_dirs/blom/hamocc/hamocc2/user_nl_blom
Labels: iHAMOCC

#447 Add info about branch structure in README.md file
  README.md
Labels: documentation

#448 Add error message if user_nl_blom includes hash comments
  cime_config/ocn_in_paramgen.py
Labels: documentation

#450 Add error message if user_nl_blom includes hash comments
  cime_config/ocn_in_paramgen.py
Labels: documentation

#451 Add error message if user_nl_blom includes hash comments
  cime_config/ocn_in_paramgen.py
Labels: documentation

#449 Add time attributes to be cdo/xr-conform
  hamocc/mo_inventory_bgc.F90
Labels: enhancement, iHAMOCC

#453 R1.4 update ci02
  .github/workflows/ci.yml
Labels: CI/meson

#455 Fix CI test system
  .github/workflows/ci.yml
Labels: CI/meson

#456 Fix CI test system
  .github/workflows/ci.yml
Labels: CI/meson

#454 Temperature- and O2-dependent sediment remineralization
  hamocc/mo_powach.F90
Labels: enhancement, iHAMOCC

#457 Remove unsupported WW3 tests from aux_blom_noresm
  cime_config/testdefs/testlist_blom.xml
Labels: invalid

#458 Update buildlib, buildlib_2.1, buildlib_2.2
  cime_config/buildlib
  cime_config/buildlib_2.1
  cime_config/buildlib_2.2
Labels: invalid

#459 Update buildlib, buildlib_2.1, buildlib_2.2
  cime_config/buildlib
  cime_config/buildlib_2.1
  cime_config/buildlib_2.2
Labels: invalid
