Repository NorESMhub/BLOM, pull requests merged in 2024-10, with the labels that each got.

#417 Introduce if statement in N-deposition also for default iHAMOCC
  hamocc/mo_read_ndep.F90
Labels: iHAMOCC

#413 Bugfix DNRA and introduce max_limiter
  hamocc/mo_extNsediment.F90
  hamocc/mo_extNwatercol.F90
  hamocc/mo_ocprod.F90
  hamocc/mo_param_bgc.F90
Labels: bug, iHAMOCC, code release

#419 Bugfix DNRA and introduce max_limiter
  hamocc/mo_extNsediment.F90
  hamocc/mo_extNwatercol.F90
  hamocc/mo_ocprod.F90
  hamocc/mo_param_bgc.F90
Labels: iHAMOCC

#420 Dust fluxes output and add descriptions in the xml-namelist file
  cime_config/buildnml
  cime_config/config_component.xml
  cime_config/namelist_definition_blom.xml
  cime_config/ocn_in.readme
  hamocc/mo_accfields.F90
  hamocc/mo_bgcmean.F90
  hamocc/mo_biomod.F90
  hamocc/mo_ncout_hamocc.F90
  hamocc/mo_ocprod.F90
Labels: enhancement, iHAMOCC

#425 Revert setting of use_ARCTIC variable
  cime_config/buildcpp
  cime_config/namelist_definition_blom.xml
  phy/mod_ifdefs.F90
  phy/mod_rdlim.F90
  phy/mod_xc.F90
Labels: bug

#391 More efficient PE layout for NOINYOC compset
  bld/tnx1v4/patch.input.431
  cime_config/config_pes.xml
Labels: enhancement

#424 Introduce switch dor T- and O2-dependent remineralization
  cime_config/namelist_definition_blom.xml
  hamocc/mo_control_bgc.F90
  hamocc/mo_ocprod.F90
  hamocc/mo_param_bgc.F90
Labels: enhancement, iHAMOCC

#427 Change placement of LTO2depremin switch
  hamocc/mo_hamocc_init.F90
  hamocc/mo_param_bgc.F90
Labels: bug, iHAMOCC
