Repository NorESMhub/BLOM, pull requests merged in 2024-06, with the labels that each got.

#350 group call to apply_fedep together with other routines for external inputs
  hamocc/mo_hamocc4bcm.F90
Labels: iHAMOCC

#355 Add lon,lat info in iHAMOCC output to more comply to cdo commands
  hamocc/mo_ncout_hamocc.F90
Labels: enhancement, iHAMOCC

#359 Disable CI test for macos with openmp
  .github/workflows/ci.yml
  phy/mod_diapfl.F90
Labels: CI/meson, BLOM

#360 new mechanism for configuring noresm to send dms and bromo from ocn -> atm
  cime_config/buildnml
Labels: iHAMOCC
