Repository NorESMhub/BLOM, pull requests merged in 2024-11, with the labels that each got.

#426 Introduce shelf-sea water residence time tracer acc. to Liu et al 2019
  cime_config/buildnml
  cime_config/config_component.xml
  cime_config/namelist_definition_blom.xml
  hamocc/meson.build
  hamocc/mo_accfields.F90
  hamocc/mo_aufr_bgc.F90
  hamocc/mo_aufw_bgc.F90
  hamocc/mo_bgcmean.F90
  hamocc/mo_control_bgc.F90
  hamocc/mo_hamocc4bcm.F90
  hamocc/mo_hamocc_init.F90
  hamocc/mo_hamocc_step.F90
  hamocc/mo_ini_fields.F90
  hamocc/mo_ncout_hamocc.F90
  hamocc/mo_param1_bgc.F90
  hamocc/mo_param_bgc.F90
  hamocc/mo_preftrc.F90
  hamocc/mo_read_shelfmask.F90
  hamocc/mo_shelfsea_restime.F90
Labels: enhancement, iHAMOCC

#434 Remove CI test for macOS
  .github/workflows/ci.yml
  .gitignore
Labels: CI/meson

#436 Technical git/gitHub update: release-1.6 branch
  .github/workflows/ci.yml
  .gitignore
Labels: CI/meson

#435 Technical git/gitHub update: master branch
  .github/workflows/ci.yml
  .gitignore
Labels: CI/meson

#384 Modified setting of vertical coordinate and vertical dimension
  cime_config/buildcpp
  cime_config/buildnml
  cime_config/config_component.xml
  cime_config/config_compsets.xml
  cime_config/config_pes.xml
  cime_config/namelist_definition_blom.xml
Labels: enhancement
