Repository NorESMhub/BLOM, pull requests merged in 2025-06, with the labels that each got.

#593 Fix externals.cfg file for GSW-Fortran
  Externals_BLOM.cfg
Labels: bug, BLOM

#597 fix ODZ volume calculation
  hamocc/mo_inventory_bgc.F90
Labels: bug, iHAMOCC

#573 add new mapping for woa18 input data
  cesm/mod_cesm.F90
  cime_config/buildnml
  cime_config/namelist_definition_blom.xml
  cime_config/testdefs/testlist_blom.xml
  cime_config/testdefs/testmods_dirs/blom/woa_nuopc/user_nl_blom
  drivers/nuopc/mod_io_input.F90
  drivers/nuopc/mod_io_output.F90
  drivers/nuopc/ocn_comp_nuopc.F90
  drivers/nuopc/ocn_map_woa.F90
  drivers/nuopc/ocn_stream_dust.F90
  phy/mod_inicon.F90
Labels: enhancement

#612 Add missing parameters to nc-file attributes
  hamocc/mo_param_bgc.F90
Labels: iHAMOCC

#617 detritus remin also in DOM classes case T- and O2-dependent
  hamocc/mo_ocprod.F90
Labels: iHAMOCC
