Repository NorESMhub/BLOM, pull requests merged in 2025-02, with the labels that each got.

#475 Update release-1.6 branch
  Externals_BLOM.cfg
  cime_config/testdefs/testlist_blom.xml
Labels: iHAMOCC

#484 Update testdefs, BLOM hybrid is now default
  cime_config/testdefs/testlist_blom.xml
Labels: bug

#480 Filtering of squared buoyancy frequency and Richardson number
  cime_config/namelist_definition_blom.xml
  phy/mod_difest.F90
Labels: enhancement

#486 Provide new N-deposition files and used remapping sh-script
  cime_config/namelist_definition_blom.xml
  utils/iHAMOCC/prepare_Ndeposition/prepare_N-deposition_input.sh
  utils/iHAMOCC/prepare_Ndeposition/retrieve-data-readme.txt
  utils/iHAMOCC/prepare_Ndeposition/retrieve-data.sh
Labels: iHAMOCC

#476 Initial version for iHAMOCC restart remapping
  utils/BLOM/README.md
  utils/common/README.md
  utils/iHAMOCC/README.md
  utils/iHAMOCC/restart_remapping/README.md
  utils/iHAMOCC/restart_remapping/blom_eos.py
  utils/iHAMOCC/restart_remapping/iHAMOCC_restart_remapping.py
  utils/iHAMOCC/restart_remapping/iHAMOCC_restart_remapping_functions.py
  utils/iHAMOCC/restart_remapping/pyplot.yml
  utils/iHAMOCC/restart_remapping/yml_template.yml
Labels: enhancement, iHAMOCC

#481 Enabled parameterized wave forcing of Langmuir mixing.
  cime_config/namelist_definition_blom.xml
Labels: enhancement

#492 Abandon usage of ndep in input files, always read NHx and NOy
  hamocc/mo_read_ndep.F90
Labels: iHAMOCC

#495 fix bug in acclvl
  hamocc/mo_bgcmean.F90
Labels: bug, iHAMOCC

#496 Fix Ncycle
  hamocc/mo_extNsediment.F90
  hamocc/mo_extNwatercol.F90
Labels: bug, iHAMOCC

#494 Add a CODEOWNERS file to the BLOM repo
  .github/CODEOWNERS
Labels: documentation

#497 Fix OpenMP call in mo_read_shelfmask
  hamocc/mo_read_shelfmask.F90
Labels: iHAMOCC

#490 Add iHAMOCC support for dustflux on tnx0.5
  cime_config/namelist_definition_blom.xml
  utils/iHAMOCC/prepare_dust_deposition/regrid_dust_deposition.sh
Labels: enhancement, iHAMOCC

#500 Reset dustflx* diagnostic fields at start of ocprod
  hamocc/mo_ocprod.F90
Labels: bug

#506 Fix N-cycle coupling
  cime_config/namelist_definition_blom.xml
  drivers/mct/import_mct.F90
  hamocc/mo_control_bgc.F90
  hamocc/mo_hamocc_init.F90
  hamocc/mo_param1_bgc.F90
  hamocc/mo_param_bgc.F90
  hamocc/mo_read_ndep.F90
Labels: bug, enhancement, iHAMOCC

#507 Corrected and updated processor layouts for tnx0.5v1 grid.
  bld/tnx0.5v1/patch.input.1132
  bld/tnx0.5v1/patch.input.1270
  bld/tnx0.5v1/patch.input.1398
  bld/tnx0.5v1/patch.input.1517
  bld/tnx0.5v1/patch.input.253
  bld/tnx0.5v1/patch.input.375
  bld/tnx0.5v1/patch.input.381
  bld/tnx0.5v1/patch.input.512
  bld/tnx0.5v1/patch.input.632
  bld/tnx0.5v1/patch.input.883
  bld/tnx0.5v1/patch.input.888
  cime_config/config_pes.xml
Labels: bug, enhancement
