Repository NorESMhub/BLOM, pull requests merged in 2025-05, with the labels that each got.

#549 Set character length to 512 for all filenames
  drivers/mct/ocn_comp_mct.F90
  drivers/nuopc/ocn_comp_nuopc.F90
  hamocc/meson.build
  hamocc/mo_Gdata_read.F90
  hamocc/mo_clim_swa.F90
  hamocc/mo_inventory_bgc.F90
  hamocc/mo_kind.F90
  hamocc/mo_ncout_hamocc.F90
  hamocc/mo_read_fedep.F90
  hamocc/mo_read_ndep.F90
  hamocc/mo_read_oafx.F90
  hamocc/mo_read_pi_ph.F90
  hamocc/mo_read_rivin.F90
  hamocc/mo_read_sedpor.F90
  hamocc/mo_read_sedqual.F90
  hamocc/mo_read_shelfmask.F90
  phy/mod_dia.F90
  phy/mod_diffusion.F90
  phy/mod_forcing.F90
  phy/mod_geoenv.F90
  phy/mod_grid.F90
  phy/mod_inicon.F90
  phy/mod_rdlim.F90
  phy/mod_restart.F90
  phy/mod_swabs.F90
  phy/mod_tidaldissip.F90
  phy/mod_types.F90
  phy/mod_utility.F90
  phy/mod_wdiflx.F90
  trc/mod_tracers_update.F90
Labels: enhancement, iHAMOCC, BLOM

#552 Set default atm. N2O concentration to pre-industrial value
  hamocc/mo_param_bgc.F90
Labels: iHAMOCC

#539 Nutrient limitation output
  cime_config/namelist_definition_blom.xml
  hamocc/mo_accfields.F90
  hamocc/mo_bgcmean.F90
  hamocc/mo_carbch.F90
  hamocc/mo_ncout_hamocc.F90
  hamocc/mo_ocprod.F90
Labels: enhancement, iHAMOCC

#514 Calendar dependency of HAMOCC processes
  hamocc/mo_hamocc_init.F90
  hamocc/mo_hamocc_step.F90
  hamocc/mo_param_bgc.F90
  hamocc/mo_powach.F90
  hamocc/mo_read_ndep.F90
  hamocc/mo_sedmnt.F90
  hamocc/mo_sedshi.F90
Labels: enhancement, iHAMOCC

#534 Implement R2OMIP protocol
  cime_config/namelist_definition_blom.xml
  hamocc/mo_accfields.F90
  hamocc/mo_apply_rivin.F90
  hamocc/mo_aufr_bgc.F90
  hamocc/mo_aufw_bgc.F90
  hamocc/mo_bgcmean.F90
  hamocc/mo_control_bgc.F90
  hamocc/mo_ini_fields.F90
  hamocc/mo_inventory_bgc.F90
  hamocc/mo_ncout_hamocc.F90
  hamocc/mo_ocprod.F90
  hamocc/mo_param1_bgc.F90
  hamocc/mo_param_bgc.F90
  hamocc/mo_read_rivin.F90
Labels: enhancement, iHAMOCC
